### ISSUE TITLE
Applicant Tracking System - Updates to Job Applicant

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#11643]
From here - https://discuss.erpnext.com/t/feature-proposal-applicant-tracking-system-ats/30661

Please consider updates to the Job Applicant and creation of some new child doctypes for Job Applicant to better support an applicant tracking system in erpnext

Changes to Job Applicant

- [ ] Change applicant name and break out to First, Middle and Last Name fields
- [ ] Add address information
- [ ] Add phone number
- [ ] Add Possible Start Date - "If Hired, on what date can you start working?"
- [ ] Military Service Y/N
- [ ] If Military Service = Y then ask for Branch, Rank, Years of Service, Skills/Duties, Other Details, Discharge Status (honorable, other than honorable, dishonorable)

Add new Job Applicant Employment History doctype
- To be presented as a table in Job Applicant so the applicant can fill in previous work history.
- Fields:
- [ ] Employer
- [ ] Employer Address
- [ ] Job Title
- [ ] Supervisor Name
- [ ] Supervisor Telephone
- [ ] Job Type
- [ ] Salary Type
- [ ] Last Salary
- [ ] Start Date
- [ ] End Date
- [ ] Position Description
- [ ] Reason for Leaving
- [ ] The end date field needs a possible override of "current" or "present" if the person is still employed by that company

Add a new Job Applicant Education doctype
- To be presented as a table in Job Applicant so the applicant can fill in previous education and other experience data
- Fields:
- [ ] School Type (High School, College/University, Vocational)
- [ ] School Name
- [ ] School Address
- [ ] Number of years completed
- [ ] Graduate Y/N
- [ ] Degree/Diploma Earned Y/N
- [ ] Degree Name
- [ ] Notes

Add a new Job Applicant Training doctype
- To be presented as a table in Job Applicant so the applicant can fill in training, certifications, professional licenses, etc
- Fields:
- [ ] Training Type (General, Technical Certification, Accredited Certification, Professional License, Foreign Language)
- [ ] Date Earned
- [ ] Company
- [ ] Date Expires
- [ ] Name
- [ ] Description

Add a new Job Applicant References doctype
- To be presented as a table in Job Applicant so the applicant can give references
- Fields:
- [ ] First Name
- [ ] Last Name
- [ ] Telephone number
- [ ] Address (optional)
- [ ] Email Address
- [ ] Related Company (from employment history)
- [ ] Number Years Acquainted

All of the changes to the Job Applicant* doctypes must reflect on the associated web form so anonymous users can apply from the ERPNext website. If an administrator customizes any of the  Job Applicant* doctypes, then those changes also should appear on the web form automatically. This allows a local administrator to ask other questions, collect more data for their site specific job applicants.
