### ISSUE TITLE
Applicant Tracking System - New Job Applicant Review and Interview doctypes

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#11644]
From here - https://discuss.erpnext.com/t/feature-proposal-applicant-tracking-system-ats/30661/

Please consider adding a new doctypes called Job Applicant Review and Job Interview and other child docytpes to better support an applicant tracking system in erpnext hr

Add a new Job Applicant Review docytpe
- The purpose of this document type is to create a place where a recruiter can intake an applicant and then gather all pertinent information about interviews, questions asked, score, etc.
- From the Job Applicant form, there would be a button to "intake applicant" that would create a review document
- If you move an applicant to review phase, then the status goes from open to "in review" on job applicant document
- Fields:
- [ ] Recruiter - (linked to employee list, maybe a new role in setup to create a filter - auto populate with current logged on user)
- [ ] Interested (Yes, Maybe, No)
- [ ] Status (New, In Review, Phone Screened, Interview Scheduled, Interviewed, Do Not Hire, Progress to Hire)
- [ ] Link to Job Opening
- [ ] Read only fields (but visible on the review document pulled from job opening document) are: title, opening date, closing date, hiring manager
- [ ] Link to Job Applicant
- [ ] Read only fields (but visible on the review document pulled from job applicant document) are: first name, last name, phone number, email address
- [ ] Notes Log - would work like the comments area on the form. As the recruiter has conversations with the applicant or the hiring manager then he/she can add a note here as they go. Then all of them are organized by date/time stamp in descending order (newest on the top)
- [ ] Table of Job Applicant interview Question Records w/ Links (see below)
- [ ] Table of Job Applicant Score Records w/ links (see below)

Add a new Job Applicant Interview doctype
- The purpose of this doctype is to manage job interviews for the candidate
- Can be managed from the Job Applicant Review document with a button (create interview). 
- Fields:
- [ ] Date
- [ ] Time
- [ ] Location Address
- [ ] Meeting Room
- [ ] Interviewer (e.g. the hiring manager, but could be another person)
- [ ] Table of Job Applicant Interview Score records w/ Links (see below)
- When an interview is created, the system will email an ICS invite to the interviewer and interviewee so they can add to their personal calendar.
- The interviewer would get a separate email with a link to the associated Job Applicant Interview Score document for the particular interview to fill in during or after the interview.

Add a new Job Applicant Interview Questions & Job Applicant Interview Questions Template doctypes
- The purpose of these doctypes is to allow a recruiter to work with varying hiring managers and develop lists of interview questions and to capture answers when used.
- The lists could have a type, such as "phone screen", "first round", "reference" or others to differentiate the lists.
- These doctypes would work very similar to the Appraisal Template and Appraisal doctypes  that already exist in HR.
- A lot of companies have highly standardized hiring procedures and questions that candidates must be asked as part of the interviewing process. These doctypes allow for the standardization and capture of all questions and the answers.
- To be seen on the Job Applicant Review document as a table.
- I don't list fields here as I am not sure exactly what would be needed.
	

Add a new Job Applicant Score & Job Applicant Score Template doctypes
- The purpose of these doctypes is to capture candidate scoring scores from a Job Applicant Score template document
- The doctypes would work very similarly to the Appraisal Template and Appraisal doctypes that exist already in HR.
- This way an administrator and can work with his/her company HR department and develop a standard candidate scoring process for all applicants by company.
- To be seen on the Job Applicant Review document as a table and then a section below the table that takes all the scores and weights and gives a total score.
- I don't list fields here as I am not sure exactly what would be needed.

**Comment by venkatsep14** [comment]
Has any of these changes added?
