### ISSUE TITLE
Applicant Tracking System - Update to Job Opening

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#11642]
From here - https://discuss.erpnext.com/t/feature-proposal-applicant-tracking-system-ats/30661

Please consider making some changes to the Job Opening doctype to support a more full featured ATS
Changes to Job Opening

- [ ] Ability to adjust the website route after initial creation/save
- [ ] Add Job Opening Date - The date the job opening was opened
- [ ] Add Job Opening Close Date - the job opening will close on this date and will automatically be unpublished from the website and the status changed to closed. Clearly hooks into the automated scheduler are needed for this one.
- [ ] Add Job Type field (Full Time, Part Time, Seasonal, Temporary, Contract, Internship, Commission)
- [ ] Add Salary Type field (per hour, per day, per week, per month, per year, and per sale (for commission))
- [ ] Add Min Salary and Max Salary fields, linked to salary type field to be able to show the min and max pay range for the job opening
- [ ] Add Location Fields (city, state) 
- [ ] Add link to Company docytype to show which company the job is for
- [ ] Add link to Employee for "Hiring Manager"

**Comment by djpalshikar** [comment]
Please also consider adding Structured Data :
https://developers.google.com/search/docs/advanced/structured-data/job-posting
