### ISSUE TITLE
User Permissions Redesign

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#12740]
Reference: https://discuss.erpnext.com/t/v11-proposal-user-permissions-redux/33013

------

### TODO

- [x] Remove "Apply User Permissions" in doctype JSONs
- [x] In List View, indicate that the view is filtered.
- [x] Remove Checkbox from "User Permission"
- [x] Tests for `db_query`
- [x] Optional "check" in Employee if User Permission has to be created or not.

------

User Permissions is still a pain. On ERPNext Cloud the highest number of setup queries are regarding user permissions and we need to fix it.

The core reason this fails is that there 3 keys to user permissions

1. User
2. Role
3. DocType

and you need to edit two views to set them

- Role Permission Manager (Apply User Permission - select doctypes)
- Make “User Permission” Rules.

**This is NO VIEW that helps you to understand the permissions**

### Proposal

Remove roles from user permissions

How this will help? There will be only one view to set user permissions, just create the “User Permission” records and based on this, the user will see only those which the user has been assigned for that doctype (not extrapolated to user)

## Use Case

Restrict User A to Project X and Y

### Before

This has probably 15 steps

1. Go to all DocTypes (like Tasks, Invoices, Expenses) that have “Project” link and check “Apply User Permission”
2. Select “Project” DocType in each of them
3. Create “User Permission” record for User A for Projects X and Y
4. Pray

Expected outcome:

All Tasks, Invoices, Expenses etc restricted for User A to Projects X & Y

(Note: provided, the user does not have another role that allows)

### After

1. Create User Permission record for User A to restrict Project X & Y
2. Relax

Expected outcome:

User A restricted to all transactions that have “Project” link to Projects X & Y

Ignore User Permissions check?
That will still apply!

Please let us know your views!

#### Edit:

We can also apply granular permissions by adding an option in “User Permissions” to apply to all linked DocTypes or specific ones.

Role permissions stay as it is.

**Comment by manassolanki** [comment]
One more issue related to the user permission usability (User permission for the nested structures)
https://github.com/frappe/erpnext/issues/9411

**Comment by kennethsequeira** [comment]
Consider document level permissions as well in this! https://github.com/frappe/erpnext/issues/9127

**Comment by shreyashah115** [comment]
#12718

**Comment by surajshetty3416** [comment]
https://github.com/frappe/erpnext/issues/10919
