### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by vjFaLk** [frappe/erpnext#5231]
### Todo
- [ ] Update images 
- [ ] Update pages with better content (1)
- [ ] Update video tutorials
- [ ] Add missing documentation for features
- [ ] Add video tutorial links to text tutorial
- [ ] Update / Clean up Wiki
- [ ] Fix broken links

#### (1) Pages To Update - 

- [ ] Emails

**Comment by TanujW** [comment]
Fix broken links?
