### ISSUE TITLE
Feature Request - Company Relationships / Consolidation of Financial Statements

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#7025]
The thread at [discuss.erpnext - Consolidation of Financial Statements](https://discuss.erpnext.com/t/consolidation-of-financial-statements/10337/10) discusses the implementation of features in ERPNext that allow for Consolidated Financial Statements.  Since ERPNext already supports the creation of multiple companies, Consolidaiton is the next logical step.  I have outlined three phases for a full-feature implementation of this concept in ERPNext.

In it, user revant_one@discuss.erpnext.com has stated using this guide as an example.
[Consolidation example](
http://www.ifrsbox.com/consolidation-example/)

Here is a 10 minute video
[Example:How To Consolidate](https://www.youtube.com/watch?v=ess7UICI17w)

I have reviewed it and consider it sufficiently adequate to proceed in creating initial DocType as per revant_one's suggestion, since it is based on [**IFRS (International Financial Reporting standards)**
](http://www.ifrs.org/About-us/Pages/What-are-IFRS.aspx)
NOTE: For consolidation to be effective, accounts from "Parent" must be **mapped** to accounts from "Child" or "Sister". Some sort of DocType (or child table) must be created, similar to a **Salary Structure** which shows the Tree of Accounts of Parent company and maps to Tree of Accounts of  **Sister or Child** company.  This should be called **Consolidation Map**.  There should be one, and only one **Consolidation map** for each child company, and a Parent Company will have several consolidation maps, describing its relationship to "n" number of companies.
1. Combine  (add up like items, such as cash, Property, Plant & Equipment)
2. Eliminate (carrying amount of parent's investment in subsidiary, parent portion of equity in each subsidiary, recognize non-controlling interest,  and goodwill)
3. Intragroup Transactions (Eliminate all transactions between the group, so, receivables from child is eliminated, and payables to parent are also eliminated)

**Phase 1**
So here is the proposed road map to enable ERPNext to Consolidate Financial Statements.
- [x] Create small pull request **Company Relationships**  (this issue)

- [x] Add child table on **Company** instead of Separate DocType.

1. Parent is **Company** and **Child Table** entries are % holdings in companies.
2. Basic Fields:  Company (link) and Percentage being held by Parent of that company

- [x] Validate Company roles with UI on Child Tables, e.g. Parent company cannot be in Child Table.

- [ ] Create **Consolidation Map** functionality, linking parent tree of accounts to child/sister tree of accounts, and establishing the relationship for EACH account:  **Combine**, **Eliminate**, **Intragroup Transaction**.  For those transactions involving post-acquisition retained earnings or non-controlling interest, a % corresponding to the stake held by parent must be added to the formula that "eliminates".  Consolidation map depends on category such as "Sister/Child"  defined in the map.  Perhaps a threshold can be set, so that  x% >= uses "sister -like" consolidation, anything < x% uses "child - like" consolidation.

- [ ] Create Goodwill table.  I am not 100% sure how to set this up right now. perhaps for Phase 3

**Phase 2**
- [ ] For each Company enable a section with Child Table named **Stock Structure**, where Stock Name, Stock Type, Amount of Stock, Date of Issue, and other characteristics such as voting rights are listed.  (Lists the entire, stock structure for a company)

- [ ] For each Parent Company, the Company Relationship section allows a Child Table listing: Child/sister company, Share type owned (link), amount owned, date of acquisition, (link to journal entry?)

- [ ] For each Parent Company, the Company Relationship section allows a Child Table listing: Child/sister company, Share type owned (link), amount owned, date of acquisition, (link to journal entry?)  This portion allows automatic calculation of % stake in child/sister company, eliminating the need for directly entering % stake as in phase 1.

- [ ] For each parent company, the stocks listed on the Company Relationship section can have a command or link that allows you to "buy/sell", basically, creating a journal entry booking the sale or purchase), to a party (Supplier/Customer)

- [ ] In Accounts>Accounting Statements> Balance sheet,  the drop down menu or other such device allows to Consolidate the Statements.  However, consider allowing for total consolidation or partial consolidation!  Partial consolidation would be by the use of a checkbox where you select only those companies you wish to include in the statements.

**Phase 3**
- [ ] Incorporate goodwill table specifying how goodwill will be recognized and on which date.  Can have several goodwill recognition amounts, and several dates, for "acquisitions in stages"

- [ ] Add functionality for
Form of **Transferred Consideration** (Cash, share issue, contingent consideration, etc.)
Selecting measurement for **Non-controlling interest** (Fair value or Proportionate Share)
Eliminating **unrealized profit**
Adjusting unrealized profit and/or depreciation charge for **Transfer of property, plant and equipment at profit within the group**
Categorizing **Goodwill** (Positive, negative or Impaired)
Selecting whether net assets are stated at **fair value** or **other value** or maybe even **not recognized**
Labelling accounts as **pre-acquisition retained earnings** and **post-acquisition retained earnings** so they can be differentiated and dealt with accordingly.

**Comment by revant** [comment]
https://github.com/frappe/erpnext/pull/7029

**Comment by revant** [comment]
Added server side validation for 3 things

 - Check Parent cannot hold its own shares
 - Check percentage holdings cannot be negative or 0
 - Error when Same Company is entered multiple times in stock structure

 @Tropicalrambler any other validations?

https://github.com/frappe/erpnext/pull/7029/commits/c259bc03a4390bc071604ec06869a8a3fec18798

**Comment by Tropicalrambler** [comment]
So far, I think this should suffice.  we'll figure out any other issues in further releases.

**Comment by revant** [comment]
> Create Consolidation Map functionality, linking parent tree of accounts to child/sister tree of accounts, and establishing the relationship for EACH account: Combine, Eliminate, Intragroup Transaction. For those transactions involving post-acquisition retained earnings or non-controlling interest, a % corresponding to the stake held by parent must be added to the formula that "eliminates". Consolidation map depends on category such as "Sister/Child" defined in the map. Perhaps a threshold can be set, so that x% >= uses "sister -like" consolidation, anything < x% uses "child - like" consolidation.

How to handle this?

 * User will save the sister/child companies in Relationships child table.
 * on Save of Company Master which has child companies, accounts must be linked.
 * Where to link accounts? Child Table  / Code Field in Account Doctype? Separate Consolidation Map Doctype?

Any Ideas?

**Comment by mhbu50** [comment]
+1

**Comment by Devens** [comment]
+1

**Comment by fikrut** [comment]
+ 1

**Comment by jof2jc** [comment]
+1

**Comment by Tropicalrambler** [comment]
I've posted on issue #7029  and here... 

Mock Up:
<img width="637" alt="screen shot 2017-03-30 at 8 40 47 pm" src="https://cloud.githubusercontent.com/assets/16600935/24534202/a264a18e-1589-11e7-996f-e1f254b0d8a4.png">

Close up:
<img width="773" alt="screen shot 2017-03-30 at 8 41 04 pm" src="https://cloud.githubusercontent.com/assets/16600935/24534203/a68b3048-1589-11e7-8804-72fd05c0fa33.png">

Close up part 2
<img width="795" alt="screen shot 2017-03-30 at 8 41 21 pm" src="https://cloud.githubusercontent.com/assets/16600935/24534206/abd6c3f0-1589-11e7-9285-9e3b2bbe4136.png">

**Comment by tundebabzy** [comment]
@Tropicalrambler
Can you point me to work done on this thus far

**Comment by Tropicalrambler** [comment]
@tundebabzy I'm still working on this. I have restructured my business recently, and these issues are now on the pipeline for proposing code. I estimate late September for this, as this issue is top on our list of requirements. I'll let you know then.

**Comment by giuseppelamatrice** [comment]
+1

**Comment by tundebabzy** [comment]
Hi @Tropicalrambler 
What's the status on this issue?
